name: electrician_app
description: An app for electricians.

publish_to: 'none'

version: 1.0.20+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^9.2.0

  #dateFormat
  intl: 0.20.2



  #make request to api
  retrofit: ^4.1.0
  dio: ^5.0.0

  # Firebase
  # firebase_core: ^2.24.0
  # cloud_firestore: ^4.13.3
  # firebase_storage: ^11.5.5

  # Gallery
  image_picker: ^1.2.1

  #Hooks
  flutter_hooks: ^0.21.3+1

  #chached image 
  cached_network_image: ^3.3.1
  google_fonts: ^6.3.3
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.9.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  dartz: ^0.10.1
  uuid: ^4.5.2
  pdf: ^3.11.3
  printing: ^5.14.2
  dynamic_color: ^1.8.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fl_chart: ^1.1.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^8.1.0

  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  freezed: ^2.5.2
  json_serializable: any
  mocktail: ^1.0.4


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/certs/
